
# 1. The universal standard port for a Config Server
server.port=8888

# 2. Application Name
spring.application.name=revplay-config-server

# 3. Where the Config Server looks for the settings (Paste your URL here!)
spring.cloud.config.server.git.uri=https://github.com/YOUR-USERNAME/revplay-config-repo.git
spring.cloud.config.server.git.default-label=main

# 4. Connects the Config Server to Eureka so other services can find it
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/