spring.application.name=revplay-eureka-server
# The universal standard port for Eureka
server.port=8761

# Tells Eureka it is the boss, not a client. It doesn't need to look for other registries.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false