version: '3.8'

services:
  # 1. THE DATABASE
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 8520

  # 2. THE PHONEBOOK (EUREKA)
  eureka-server:
    build: ./revplay-eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  # 3. THE CONFIG SERVER
  config-server:
    build: ./revplay-config-server
    container_name: config-server
    depends_on:
      - eureka-server
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # 4. THE TRAFFIC COP (API GATEWAY)
  api-gateway:
    build: ./revplay-api-gateway
    container_name: api-gateway
    restart: on-failure
    depends_on:
      - eureka-server
      - config-server
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # 5. THE AUTH SERVICE
  auth-service:
    build: ./revplay-auth-service
    container_name: auth-service
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/revplay_auth_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8520

  # 6. THE USER SERVICE
  user-service:
    build: ./revplay-user-service
    container_name: user-service
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/revplay_auth_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8520

  # 7. THE CATALOG SERVICE
  catalog-service:
    build: ./revplay-catalog-service
    container_name: catalog-service
    restart: on-failure
    ports:
      - "8083:8083"
    depends_on:
      - mysql-db
      - eureka-server
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/revplay_catalog_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8520

  # 8. THE PLAYLIST SERVICE
  playlist-service:
    build: ./revplay-playlist-service
    container_name: playlist-service
    restart: on-failure
    ports:
      - "8084:8084"
    depends_on:
      - mysql-db
      - eureka-server
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/revplay_playlist_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8520

  # 9. THE FAVORITE SERVICE
  favorite-service:
    build: ./revplay-favorite-service
    container_name: favorite-service
    restart: on-failure
    ports:
      - "8085:8085"
    depends_on:
      - mysql-db
      - eureka-server
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/revplay_favorite_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8520

  # 10. THE PLAYBACK SERVICE
  playback-service:
    build: ./revplay-playback-service
    container_name: playback-service
    restart: on-failure
    ports:
      - "8086:8086"
    depends_on:
      - mysql-db
      - eureka-server
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/revplay_playback_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8520

  # 11. THE ANALYTICS SERVICE
  analytics-service:
    build: ./revplay-analytics-service
    container_name: analytics-service
    restart: on-failure
    ports:
      - "8087:8087"
    depends_on:
      - mysql-db
      - eureka-server
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/revplay_analytics_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8520