spring.application.name=revplay-playlist-service
# Port 8084 is next in line! (Gateway=8080, Auth=8081, User=8082, Catalog=8083)
server.port=8084

# Connect to the Central Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Connect to her local MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/revplay_playlist_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=ahmad

# Hibernate rules
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000