# 1. Gateway Port
server.port=8080
spring.application.name=revplay-api-gateway

# 2. Eureka Connection
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# 3. ROUTING RULES FOR AUTH SERVICE
# Give the route an ID
spring.cloud.gateway.routes[0].id=auth-service
# Tell it to use Eureka (Load Balancer) to find the Auth Service
spring.cloud.gateway.routes[0].uri=lb://REVPLAY-AUTH-SERVICE
# Tell it which URL paths should go to this service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# 4. ROUTING RULES FOR USER SERVICE
# Give the route an ID
spring.cloud.gateway.routes[1].id=user-service
# Tell it to use Eureka (Load Balancer) to find the User Service
spring.cloud.gateway.routes[1].uri=lb://REVPLAY-USER-SERVICE
# Tell it which URL paths should go to this service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

# 5. ROUTING RULES FOR CATALOG SERVICE
spring.cloud.gateway.routes[2].id=catalog-service
spring.cloud.gateway.routes[2].uri=lb://REVPLAY-CATALOG-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/songs/**,/api/albums/**

spring.cloud.gateway.routes[3].id=playlist-service
spring.cloud.gateway.routes[3].uri=lb://REVPLAY-PLAYLIST-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/playlists/**