
# The gateway takes your main port. Angular will talk to THIS port.
server.port=8080

# The name that will show up in the Eureka Dashboard
spring.application.name=revplay-api-gateway

# Points the Gateway to Eureka so it can find the other services
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/