# 1. Gateway Port
server.port=8080
spring.application.name=revplay-api-gateway

# 2. Eureka Connection
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# 3. ROUTING RULES FOR AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://REVPLAY-AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# 4. ROUTING RULES FOR USER SERVICE
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://REVPLAY-USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

# 5. ROUTING RULES FOR CATALOG SERVICE
spring.cloud.gateway.routes[2].id=catalog-service
spring.cloud.gateway.routes[2].uri=lb://REVPLAY-CATALOG-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/songs/**,/api/albums/**

# 6. ROUTING RULES FOR PLAYLIST SERVICE
spring.cloud.gateway.routes[3].id=playlist-service
spring.cloud.gateway.routes[3].uri=lb://REVPLAY-PLAYLIST-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/playlists/**

# 7. ROUTING RULES FOR FAVORITE SERVICE
spring.cloud.gateway.routes[4].id=favorite-service
spring.cloud.gateway.routes[4].uri=lb://REVPLAY-FAVORITE-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/favorites/**

# ? FIX: NEW ROUTING RULES FOR PLAYBACK (HISTORY) SERVICE
spring.cloud.gateway.routes[5].id=playback-service
spring.cloud.gateway.routes[5].uri=lb://REVPLAY-PLAYBACK-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/history/**

# 8. ROUTING RULES FOR ANALYTICS SERVICE
spring.cloud.gateway.routes[6].id=analytics-service
spring.cloud.gateway.routes[6].uri=lb://REVPLAY-ANALYTICS-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/analytics/**

eureka.instance.prefer-ip-address=true

# --- GLOBAL CIRCUIT BREAKER ---
spring.cloud.gateway.default-filters[0].name=CircuitBreaker
spring.cloud.gateway.default-filters[0].args.name=globalCircuitBreaker
spring.cloud.gateway.default-filters[0].args.fallbackUri=forward:/fallback

# --- RESILIENCE4J SETTINGS ---
resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.timelimiter.configs.default.timeout-duration=5s


# --- CORS CONFIGURATION (ALLOW ANGULAR FRONTEND) ---
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true